# Generated by Django 4.1.5 on 2023-01-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_benh', models.CharField(max_length=200)),
                ('kh', models.CharField(max_length=50)),
                ('nguyen_nhan', models.TextField(blank=True)),
                ('dieu_tri', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrieuChung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('ki_hieu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GiaTri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trongso', models.IntegerField(default=1)),
                ('gia_tri', models.FloatField(default=0)),
                ('benh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.benh')),
                ('tc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.trieuchung')),
            ],
        ),
    ]
