# Generated by Django 4.1.5 on 2023-01-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('matkhau', models.CharField(max_length=45)),
            ],
        ),
    ]
