# Generated by Django 4.1.5 on 2023-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_benhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhan',
            name='ngaychuandoan',
            field=models.DateTimeField(blank=True),
        ),
    ]
